name = "bizwiz3/lunemon"
version = "0.1.0"
description = "A hot-reloading development tool for Lune, inspired by Nodemon."
license = "MIT"
authors = ["BizWiz3"]
repository = "https://github.com/BizWiz3/lunemon"
private = false

[target]
environment = "lune"
bin = "src/lunemon.luau"

includes = ["LICENSE", "README.md", "lunemon.luau", "pesde.toml"]

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
hello = { name = "pesde/hello", version = "^1.0.2" }
