name = "bizwiz3/lunemon"
version = "0.1.1"
description = "A hot-reloading development tool for Lune, inspired by Nodemon."
license = "MIT"
authors = ["BizWiz3"]
repository = "https://github.com/BizWiz3/lunemon"
private = false

includes = ["LICENSE", "README.md", "src/lunemon.luau", "pesde.toml"]

[target]
environment = "lune"
bin = "src/lunemon.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
